CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY,
	Username VARCHAR(30) UNIQUE NOT NULL,
	Password VARCHAR(25) NOT NULL,
	ProfilePicture VARBINARY(900),
	LastLoginTime DATETIME2,
	IsDeleted BIT 
)

INSERT INTO Users VALUES
('A', 'A', NULL, GETDATE(), 0),
('B', 'A', NULL, GETDATE(), 0),
('C', 'A', NULL, GETDATE(), 0),
('D', 'A', NULL, GETDATE(), 0),
('E', 'A', NULL, GETDATE(), 0)

ALTER TABLE Users
 DROP CONSTRAINT PK__Users__3214EC07E10CCDCD;

ALTER TABLE Users
  ADD CONSTRAINT PK_CompositeKey PRIMARY KEY (Id, Username)

ALTER TABLE Users
  ADD CONSTRAINT CHK_Password CHECK (Password >= 5)

  ALTER TABLE Users
    ADD CONSTRAINT LLT_Default
DEFAULT GETDATE() FOR LastLoginTime

ALTER TABLE Users
 DROP CONSTRAINT PK_CompositeKey;

 ALTER TABLE Users
  ADD CONSTRAINT PK_Pk PRIMARY KEY (Id)

ALTER TABLE Users
  ADD CONSTRAINT CHK_Username CHECK (Username >= 3)